package com.killrvideo.graphql.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

import com.killrvideo.dse.model.Comment;

/**
 * In KillrVideo each video holds a list of comments.
 */
public class CommentGQL implements Serializable {
    
    /**
     * Serial.
     */
    private static final long serialVersionUID = -4032110812123661790L;

    /**
     * Unique identifier for a user (tech id)
     */
    protected String userid;
    
    /**
     * Unique identifier for a video (tech id)
     */
    protected String videoid;

    /**
     * Text of the comment
     */
    protected String comment;
    
    /**
     * Unique identifier for a comment, generated by the system (tech id)
     */
    protected String commentid;
     
    /**
     * Insertion date of the comment
     */
    private Date dateOfComment;

    
    public CommentGQL() {
    }
    
    public CommentGQL(Comment dto) {
        this.comment   = dto.getComment();
        this.commentid = dto.getCommentid().toString();
        this.userid    = dto.getUserid().toString();
        this.videoid   = dto.getVideoid().toString();
        this.dateOfComment = dto.getDateOfComment();
    }
    
    public Comment toCommentDto() {
        Comment c = new Comment();
        c.setComment(this.comment);
        c.setDateOfComment(this.dateOfComment);
        c.setCommentid(UUID.fromString(this.getCommentid()));
        c.setVideoid(UUID.fromString(this.getVideoid()));
        c.setUserid(UUID.fromString(this.getUserid()));
        return c;
    }
    
    /**
     * Getter accessor for attribute 'userid'.
     *
     * @return
     *       current value of 'userid'
     */
    public String getUserid() {
        return userid;
    }

    /**
     * Setter accessor for attribute 'userid'.
     * @param userid
     * 		new value for 'userid '
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * Getter accessor for attribute 'videoid'.
     *
     * @return
     *       current value of 'videoid'
     */
    public String getVideoid() {
        return videoid;
    }

    /**
     * Setter accessor for attribute 'videoid'.
     * @param videoid
     * 		new value for 'videoid '
     */
    public void setVideoid(String videoid) {
        this.videoid = videoid;
    }

    /**
     * Getter accessor for attribute 'comment'.
     *
     * @return
     *       current value of 'comment'
     */
    public String getComment() {
        return comment;
    }

    /**
     * Setter accessor for attribute 'comment'.
     * @param comment
     * 		new value for 'comment '
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter accessor for attribute 'commentid'.
     *
     * @return
     *       current value of 'commentid'
     */
    public String getCommentid() {
        return commentid;
    }

    /**
     * Setter accessor for attribute 'commentid'.
     * @param commentid
     * 		new value for 'commentid '
     */
    public void setCommentid(String commentid) {
        this.commentid = commentid;
    }

    /**
     * Getter accessor for attribute 'dateOfComment'.
     *
     * @return
     *       current value of 'dateOfComment'
     */
    public Date getDateOfComment() {
        return dateOfComment;
    }

    /**
     * Setter accessor for attribute 'dateOfComment'.
     * @param dateOfComment
     * 		new value for 'dateOfComment '
     */
    public void setDateOfComment(Date dateOfComment) {
        this.dateOfComment = dateOfComment;
    }

}
